### ISSUE TITLE
Show link to the repository in package list

### ISSUE THREAD

**Issue by Raphael-CV** [typst/packages#109]
I suggest two improvements for the package manager:
- Add the repository link of each package in its readme file and/or in the [searchable list](https://typst.app/docs/packages/) of packages. Currently, you need to go to the `typst.toml` file and copy-paste the link into navigator, which is annoying when you want to see the full documentation and examples. Add also the link in the pull request would be great to navigate easily to the repo in order to discover it instead of going to `files changed` and look for `typst.toml` file.

- Add a command to install package from an already downloaded zip. Automatic downloads can be blocked at work for security reasons (which is the case for me). I also reckon that add a link to download directly zip in the searchable list of packages might be a good idea. For the moment, if I want to download several packages, I have to go to each repo, check out the branch or tag to have the right version, donwload zip, copy-paste to the `preview` directory and then change the name with version to respect the tree structure.

**Comment by laurmaedje** [comment]
> For the moment, if I want to download several packages, I have to go to each repo, check out the branch or tag to have the right version, donwload zip, copy-paste to the preview directory and then change the name with version to respect the tree structure.

You could also just clone this repository into `{cache-dir}/typst`. Then all packages will just be available. To update it, just `git pull`. Then, the CLI will do no downloading at all.

**Comment by Raphael-CV** [comment]
Great idea, it seems better indeed, thanks !

**Comment by laurmaedje** [comment]
Repository link in the package list would be useful. It could show homepage or repository if also add a homepage field as suggested here: https://github.com/typst/packages/issues/67#issuecomment-1663102592

**Comment by Raphael-CV** [comment]
> > For the moment, if I want to download several packages, I have to go to each repo, check out the branch or tag to have the right version, donwload zip, copy-paste to the preview directory and then change the name with version to respect the tree structure.
> 
> You could also just clone this repository into `{cache-dir}/typst`. Then all packages will just be available. To update it, just `git pull`. Then, the CLI will do no downloading at all.

Since the structure has to be `{data-dir}/typst/packages/preview/...`, it is to necessary specifiy the directory name:
- From `{data-dir}`: `git clone git@github.com:typst/packages.git typst`
- From `{data-dir}/typst`: `git clone git@github.com:typst/packages.git .`

Doing `git clone git@github.com:typst/packages.git` from `{data-dir}/typst` would result to `{data-dir}/typst/packages/packages/preview/...`.

**Comment by laurmaedje** [comment]
Ah yes, you're right. The duplication is somewhat unfortunate.

**Comment by laurmaedje** [comment]
I added a link to the `repository` and, in addition, a new `homepage` field. If this one, is specified, the link goes there, otherwise to the repository and if neither field exist, it is omitted.
