### ISSUE TITLE
Proposal to rename this repository to something more identifiable

### ISSUE THREAD

**Issue by figsoda** [typst/packages#13]
### Proposal

I am proposing to rename this repository to something more identifiable, e.g. `typkgs`, instead of `packages` which is what we have right now. This is a very common pattern with repositories like `crates.io`, `pypi`, and `npm`

### Motivation

- This will give it a shorter and canonical name to refer to: `typkgs` vs. `typst package repository`
- Open up possibilities for alternative package repositories. If alternative package repositories or packages without repositories were to be implemented. Renaming this will make it less ambiguous and reduce the potential confusion.
- Third party tooling: This will make naming third party tools that interact specifically with this repository easier.

### Drawbacks

- This is a rename and people will need to adapt to the changes. The impact is minimal if we do this early, since GitHub will be able to handle the redirects.
- Opportunity for bike shedding: Naming is hard, and people will have different opinions. This is not much of an issue for something generic like `packages`.

**Comment by laurmaedje** [comment]
> Easier to search

For me it showed up as the second hit after typst/typst and the package list in the docs showed up search. Maybe Google just needed a bit of time?

**Comment by laurmaedje** [comment]
I like the current name and it is also in line with the domain used to serve the packages (packages.typst.org) and that can't change at this point. 

> This will give it a shorter and canonical name to refer to

That's fair enough, but I don't think it's that much of an issue to call it the "typst package repository".

> Open up possibilities for alternative package repositories ... Renaming this will make it less ambiguous and reduce the potential confusion.

I don't think that this would really be blocked by the name. Besides, what's more interesting (at least to me) than completely alternate registries is team/university-local packages, but these can just be namespaces.

> ... packages without repositories were to be implemented

If we move to packages without repositories, we will most probably still keep the existing packages, we will just move to them to another storage. (Unless we decide to retire `@preview` at the same time.)

> This will make naming third party tools that interact specifically with this repository easier.

Overall, I see your points to an extent but the issues all seem pretty minor and the current name is nice and clear in my opinion, so I would refrain from changing it.

I also [asked](https://discord.com/channels/1054443721975922748/1088371867913572452/1126186543770521661) on Discord and the consensus seems to be that the current name is liked.
