### ISSUE TITLE
[README]: #import "@local/mypkg:1.0.0": * should be changed to #import "@preview/mypkg:1.0.0": *

### ISSUE THREAD

**Issue by FengChendian** [typst/packages#1320]
### Description

![image](https://github.com/user-attachments/assets/933494c6-9915-4c08-8786-dfa80d50410b)

**Comment by flokl** [comment]
The [part](https://github.com/typst/packages?tab=readme-ov-file#local-packages) of the readme which contains `#import "@local/mypkg:1.0.0": *`, explicitly talks about how to experiment with a package locally **without** publishing for everyone. `@preview` is the public namespace for packages.
