### ISSUE TITLE
colorful-boxes : Breakable boxes

### ISSUE THREAD

**Issue by maucejo** [typst/packages#136]
Hi, at the moment `colorful-boxes` (previously `typst-boxes`) does not allow for breakable boxes, which can be somewhat annoying.
My solution is to download `typst-boxes` and modify the source code.

A simple question, how to create a PR for this package. Should I fork the whole `typst/packages` repository or should I fork the original repository ?

Thank you

**Comment by Enivex** [comment]
> Hi, at the moment `colorful-boxes` (previously `typst-boxes`) does not allow for breakable boxes, which can be somewhat annoying.
> My solution is to download `typst-boxes` and modify the source code.
> 
> A simple question, how to create a PR for this package. Should I fork the whole `typst/packages` repository or should I fork the original repository ?
> 
> Thank you

You contribute to the original repository.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Also (a little bit of spam) you could try to use ``showybox`` package, it has implemented that already --and other custom options also! Here's an example of a breakable box in ``showybox``:

![image](https://github.com/typst/packages/assets/30756770/746da298-6874-46cc-984d-ad4d05157481)

**Comment by maucejo** [comment]
> Also (a little bit of spam) you could try to use ``showybox`` package, it has implemented that already --and other custom options also! Here's an example of a breakable box in ``showybox``:
> 
> ![image](https://github.com/typst/packages/assets/30756770/746da298-6874-46cc-984d-ad4d05157481)

Is it possible to replicate `slantedColorbox` of `typst-boxes` with `showybox` ?

**Comment by Pablo-Gonzalez-Calderon** [comment]
> Is it possible to replicate `slantedColorbox` of `typst-boxes` with `showybox` ?

At the moment, it's not possible, due to some limitations of v1.1.0 ``boxed`` titles. Now, v1.2.0 (kinda) is in developement and have a similar kind of box. Here's an example:

```typst
// v1.2.0 example
#showybox(
  frame: (
    radius: 0pt,
    thickness: 2pt
  ),
  title-style: (
    boxed: true
  ),
  boxed-style: (
    radius: 0pt,
    anchor: (y: bottom)
  ),
  title: "This isn't quite perfect but...",
  width: 50%,
)[#lorem(10)]
```
![image](https://github.com/typst/packages/assets/30756770/71e57135-03cd-420c-89d1-d8628a789feb)

**Comment by laurmaedje** [comment]
As said, PRs should be made to the original repository. I see you've made one already, linking it here for posterity: https://github.com/lkoehl/typst-boxes/pull/3
