### ISSUE TITLE
glossarium breaks if page numbering is not set

### ISSUE THREAD

**Issue by JuliDi** [typst/packages#176]
The "glossarium" package's example works because it does `#set page(numbering: "1", paper: "a5")`.
However, if you don't have page numbering set, e.g., because you print it manually in a custom footer, it will break in this line https://github.com/typst/packages/blob/4b8adb3f36a4d20d01e505230f481ebce6259c01/packages/preview/glossarium/0.2.2/glossarium.typ#L141

Unfortunately I am rather new to typst and don't yet have an idea how to fix it except for globally setting the page numbering as in the example.

**Comment by Dherse** [comment]
Please open the issue on the glossarium's package GitHub issue page.

https://github.com/ENIB-Community/glossarium

**Comment by JuliDi** [comment]
Sure will do, thank you.
I can't seem to find that link anywhere in the package's readme, though.

**Comment by Dherse** [comment]
Yeah, it could definitely improve, here is a lil' trick:

![image](https://github.com/typst/packages/assets/9665250/e8f3addb-ea06-44c2-bf97-f228babd04bc)

Those buttons let you go to the package's own repository ;)
