### ISSUE TITLE
[unify package] Set decimal separator manually

### ISSUE THREAD

**Issue by TheChilliPL** [typst/packages#188]
It should be possible to set the default decimal separator. I tried doing
```typ
#set _format-float(decsep: ",")

$ num("2.0") $
```
as I prefer to leave the numbers in code with dots (yet want it to show up as 2,0), but it throws a syntax error. Any way to set that in another way?

**Comment by PgBiel** [comment]
cc @ChHecker

**Comment by ChHecker** [comment]
This is currently not possible. You could open up a feature request on the [unify repository](https://github.com/ChHecker/unify). Otherwise, I could do the same for you.

**Comment by laurmaedje** [comment]
@ChHecker Good to know that there's a repo. This should probably be added to the `typst.toml` metadata so that the package list can link to it. (This would even be possible without a version bump under the minor fix policy.)
