### ISSUE TITLE
Add support for MSB first bit order

### ISSUE THREAD

**Issue by natrow** [typst/packages#198]
Currently, these diagrams show bits from 0 to N, but many diagrams of byte fields start with the MSB (N down to 0). Could support for this be added?

**Comment by laurmaedje** [comment]
Which package are you referring to?

**Comment by natrow** [comment]
Sorry, I meant for the bytefield package

**Comment by laurmaedje** [comment]
Yes, please open an issue there. For all packages that have their own repository, you can find it by clicking on the chain icon next to the package on https://typst.app/docs/packages.
