### ISSUE TITLE
content misalignment

### ISSUE THREAD

**Issue by AdiWeit** [typst/packages#200]
Like seen in the user manual (first graphic) and also in my little code example (second graphic), the content, meaning p_1, p_2, ..., is colliding with the lines/graph. It would be great if it would go a little bit more away from the point it's referring to. Maybe there's an option  that I'm missing but I think in that case the manual should change. To make clear what I mean the last image is what it should look like (I created the graph using Latex tikz)
![grafik](https://github.com/typst/packages/assets/43521682/bb3814b1-9092-47a7-ab45-74d297ae7efa)
![grafik](https://github.com/typst/packages/assets/43521682/23fd1927-36a0-415e-b58c-a06d25c0b290)
![grafik](https://github.com/typst/packages/assets/43521682/7efb24e0-0282-423f-9a64-4a641ddff3f0)

**Comment by Enivex** [comment]
Please post this on https://github.com/johannes-wolf/cetz instead
