### ISSUE TITLE
Can we have a function for Dirac slash notation? 

### ISSUE THREAD

**Issue by mandalaritra1** [typst/packages#214]
The default angle in the `cancel` function does not look good as Dirac slash. Can we have something which looks like 
slashed(D) -> `$cancel(D, angle: #18deg)$` ?

**Comment by PgBiel** [comment]
Try

```typ
#let slashed = math.cancel.with(angle: 18deg)
$slashed(D)$
```

or even

```typ
#let dirac = $cancel(D, angle: #18deg)$
$dirac$
```

**Comment by PgBiel** [comment]
Also, this is the wrong repository to open an issue related to Typst (the correct repository is github.com/typst/typst).
