### ISSUE TITLE
Glossarium not working with reference syntax -> cannot reference figure without numbering

### ISSUE THREAD

**Issue by Fabioni** [typst/packages#219]
Package: https://github.com/typst/packages/tree/main/packages/preview/glossarium/0.2.3 

Trying to replicate the demo example:

```
#print-glossary((
  // minimal term
  (key: "kuleuven", short: "KU Leuven"),
  // a term with a long form
  (key: "unamur", short: "UNamur", long: "Université de Namur"),
  // no long form here
  (key: "kdecom", short: "KDE Community", desc:"An international team developing and distributing Open Source software."),
  // a full term with description containing markup
  (
    key: "oidc", 
    short: "OIDC", 
    long: "OpenID Connect", 
    desc: [OpenID is an open standard and decentralized authentication protocol promoted by the non-profit
     #link("https://en.wikipedia.org/wiki/OpenID#OpenID_Foundation")[OpenID Foundation].]),
))

// referencing the OIDC term using gls
#gls("oidc")
// displaying the long form forcibly
#gls("oidc", long: true)

// referencing the OIDC term using the reference syntax
@oidc
```

Usage as `#gls("oidc")` does work but usage as `@oidc`does produce the following error:

> Error: cannot reference figure without numbering

I think it works under Typst 0.8.0 but not under Typst 0.9.0, so https://typst.app/docs/changelog/ might help, but I am not sure what the problem is.

**Comment by Enivex** [comment]
This should be posted to https://github.com/ENIB-Community/glossarium

**Comment by Fabioni** [comment]
my bad, I misread something

**Comment by Enivex** [comment]
> my bad, I misread something

No worries. In fact, the wrong repository was listed on the package list
