### ISSUE TITLE
[algo]: Wondering if there's support for disabling numbering on a certain line

### ISSUE THREAD

**Issue by ericbenitez** [typst/packages#242]
I was wondering if it's possible to replicate the example below, where step 5 becomes too long so we do a new line without a step number

Thanks!
![image](https://github.com/typst/packages/assets/47505497/d9108408-edfd-4893-9a31-b5a155eea759)

**Comment by laurmaedje** [comment]
Which package are you asking about?

**Comment by laurmaedje** [comment]
Please report it here: https://github.com/platformer/typst-algorithms
