### ISSUE TITLE
Physica package shadows gradient type

### ISSUE THREAD

**Issue by SolidTux** [typst/packages#265]
The physica package defines [`gradient`](https://github.com/typst/packages/blob/734e8ed0e3b28248daa52c71db285de31bb818c9/packages/preview/physica/0.8.1/physica.typ#L189), which shadows the [gradient type](https://typst.app/docs/reference/visualize/gradient). Maybe it would be better to just provide `grad`?

**Comment by tingerrr** [comment]
This should be opened over at https://github.com/Leedehai/typst-physics.
