### ISSUE TITLE
The package no longer works correctly in the latest version of Typst.

### ISSUE THREAD

**Issue by fabriceci** [typst/packages#294]
Here is a rendering of the two examples in an new empty Typst document

![Screenshot 2023-12-12 at 15 24 12](https://github.com/typst/packages/assets/6397893/81b952fa-e904-41e8-bcad-b3c4056ff913)

**Comment by laurmaedje** [comment]
This issue tracker is only for issues about the package management itself. There is already an issue on the syntree repository: https://github.com/lynn/typst-syntree/issues/1.
