### ISSUE TITLE
circular arrows for self-pointing

### ISSUE THREAD

**Issue by javentous** [typst/packages#313]
## Issue
I don't quite know how to make a circular arrow, in that it tracks the circumference of a circle, starts at a node A and ends at node A with the specified head type. Here's my code and I'll add some images.
### Code
```
#import "@preview/cetz:0.1.2"
#import "@preview/fletcher:0.2.0": *


// attempt at an expanded central dogma of biology
#fletcher.diagram(cell-size: 8mm, {
  // dg is for central dogma, i.e. the original three steps
  //   of replication, transcription, and translation
  let (dna, rna, protein) = ((0,1), (2,1), (4,1))
  node(dna, `DNA`, )
  node(rna, `RNA`)
  node(protein, `PROTEIN`)
  edge(dna, dna, `Replication`, "->", bend: 0deg)      // <--- the part i'm having issues with
  edge(dna, rna, `Transcription`, "->", bend: 10deg)
  edge(rna, dna, `Transcription`, "->", bend: 10deg)
  edge(rna, protein, `Translation`, "->")
})
```
#### Without trying to make a circular arrow (i.e. line of interest commented out)
<img width="320" alt="image" src="https://github.com/typst/packages/assets/12705383/d8d9c228-37a0-491c-9a4d-c03c3bea39e3">

#### Trying to make a circular arrow
<img width="350" alt="image" src="https://github.com/typst/packages/assets/12705383/f2541f3d-edf5-41c2-8744-319ca5240ac8">

#### Reference image for what I'd like to do
<img width="793" alt="image" src="https://github.com/typst/packages/assets/12705383/a44c41c0-9b66-46b6-8434-98122732b17a">

###### PS
Hey, thanks for the package, i tried working on one a while back for cetz (when it was called something else) but never figured out how to make it work. Tried to think of how to implement a simple pathing algo (djikstra's) for a timeline maker thing but left after I learned that there are these things things called ASTs

**Comment by Enter-tainer** [comment]
issues should go https://github.com/johannes-wolf/cetz
