### ISSUE TITLE
Could you add my cn-num package to packages list?

### ISSUE THREAD

**Issue by soarowl** [typst/packages#317]
The package url is: [cn-num](https://github.com/soarowl/cn-num.git)

Convert Arabic numbers to Chinese numbers. I think it's useful for Chinese community.

Best regards,

Zhuo Nengnwen

**Comment by laurmaedje** [comment]
You can submit your package through a pull request. See [the guidelines](https://github.com/typst/packages?tab=readme-ov-file#submission-guidelines). Note that the name would need to be changed for inclusion in the package repository as it is too obvious and descriptive as is.
