### ISSUE TITLE
Documentation Colorful-Boxes is incorrect

### ISSUE THREAD

**Issue by Aevyz** [typst/packages#321]
Readme for Colorful-Boxes 1.2.0 claims

```
#slanted-colorbox(
  title: lorem(5),
  color: "red",
  radius: 0pt,
  width: auto
)[
  #lorem(50)
]
```

when the code refers to `#let slantedColorbox(title: "title", color: none, radius: 0pt, width: auto, body) = {`

https://github.com/typst/packages/blob/main/packages/preview/colorful-boxes/1.2.0/lib.typ#L59C1-L60C1

Probably, this fix needs to be done by @Loewe1000

**Comment by laurmaedje** [comment]
Please open an issue here instead: https://github.com/lkoehl/typst-boxes
