### ISSUE TITLE
Weird edge case 

### ISSUE THREAD

**Issue by ondohotola** [typst/packages#33]
The following code

```typst
#import "@preview/showybox:0.1.1": *
#show link: it => { text(blue, it.body) }
#showybox(
  title: [
    Title#footnote[
      https://google.com
    ]
  ],
)[
  https://github.com
]
```

renders correctly, however, while the **Github** link points to `https://github.com` the **Google** link (in the footnote) points to `http://google.com` instead of `https://google.com`.

If I **remove** `#show link: it => { text(blue, it.body) }` it points to `https://google.com`.

**Comment by laurmaedje** [comment]
The show rule overrides the links default behaviour. Viewers then still recognize the link from the text, but depending on the viewer different things happen. Chrome seems to get it right while Apple Preview does the http thing.

Whether a link show rule should or shouldn't remove the link's behaviour of, well, making a link is a valid question. However, it is in any case a typst/typst question and not related to the package repository.

**Comment by laurmaedje** [comment]
What you want to use here is either:
```
#show link: it => { text(blue, it) }
```
or just
```
#show link: set text(blue)
```
So `it` instead of `it.body` to retain the links default behaviour.

**Comment by ondohotola** [comment]
Thank you
