### ISSUE TITLE
typo in units.scv

### ISSUE THREAD

**Issue by porcaror** [typst/packages#332]
I realized that there is a typo in the file units.csv (in fact the colulomb unit doesn't work).
To fix it I think it is necessary to remove the character " as in the picture.
Thank you.
[units.csv.pdf](https://github.com/typst/packages/files/13857967/units.csv.pdf)

**Comment by max397574** [comment]
not sure which units.csv file you're talking about
but it likely is part of a package and you should open this issue in the package repo

**Comment by laurmaedje** [comment]
Please open issue on https://github.com/ChHecker/unify
