### ISSUE TITLE
Link to packages original github from the webpage

### ISSUE THREAD

**Issue by xd009642** [typst/packages#352]
### Description

So when I click the link of a package on the website, I want to ideally go to the repo as this may have examples, issues, links to other things like books which the release/summary thing on this repo for a package doesn't have. So either change the link to be github or add another button for the repo so users can navigate to the packages repo.

**Comment by laurmaedje** [comment]
The chain icon on the right links to the repo. Since it's optional and the main link is guaranteed to exist, I'd prefer not to swap them.

**Comment by xd009642** [comment]
Oh  doh, I hovered over the  chain but for some reason though it was the same link. Never mind then
