### ISSUE TITLE
Macro in column operator increase newlines

### ISSUE THREAD

**Issue by pacaunt** [typst/packages#353]
### Description

I tried to apply a typst function `math.upright` to a certain cells, but after applying them, newlines are increasing leading the table. So I tested by change the function in the macro to `math.sqrt` and the following picture was captured.
![Screen Shot 2567-01-20 at 23 21 40](https://github.com/typst/packages/assets/157231794/94f1d0c9-8690-4325-8545-8eff21d77469)
Is this considered a bug? Or I used the macro feature improperly?

**Comment by Enter-tainer** [comment]
can you show the full code? looks like you are using custom syntax to render a table

**Comment by laurmaedje** [comment]
Please open tbl-related issues here: https://github.com/maxcrees/tbl.typ
