### ISSUE TITLE
typos in funarray	package description

### ISSUE THREAD

**Issue by slashformotion** [typst/packages#43]
![image](https://github.com/typst/packages/assets/45801817/d8d50714-d4c4-4359-9f52-d9214787920d)

`Package providing convinient functional functions to use on arrays.` => `Package providing convenient functional functions to use on arrays.`

**Comment by laurmaedje** [comment]
I don't touch package contents myself, but @ludwig-austermann is free to submit a fix PR (under the minor-doc-fix-is-okay policy).

**Comment by laurmaedje** [comment]
Going to close this as there's nothing more to be done from our side, the possibility of a fix PR is of course still there.
