### ISSUE TITLE
Tiaoma readme typo. Should I edit it inplace or publish a new version?

### ISSUE THREAD

**Issue by Enter-tainer** [typst/packages#445]
### Description

https://github.com/typst/packages/tree/main/packages/preview/tiaoma/0.2.0#example I just realized I forget to update the version number in readme of tiaoma 0.2.0: the code block in readme still remains 0.1.0.

Should I edit it inplace? Or I need 0.2.1 to fix this?
<img width="451" alt="image" src="https://github.com/typst/packages/assets/25521218/5d8f7523-b145-4d16-8d1e-a97f1ad448a4">

**Comment by laurmaedje** [comment]
You can edit the README in place. It counts as a minor fix since it does not affect the functionality or the code of the package. (A bug fix for instance wouldn't be allowed since users could already have a cached faulty version.)
