### ISSUE TITLE
Description for cumcm-muban includes link to non-free font

### ISSUE THREAD

**Issue by Enivex** [typst/packages#499]
### Description

This may not be the correct venue for this, but I'm not sure what is. It's not really an issue with the package system, but it's also not (directly) an issue with the package.

On https://typst.app/universe/package/cumcm-muban there is a link to a zip-file at the bottom.

This zip file contains several fonts that aren't free (including Times New Roman). This was presumably done because the package author was told not to include them in the package, but linking to them is only marginally better. The correct way of dealing with this is to inform the user which fonts are needed, and it would then be up to them to get a hold of them.

**Comment by laurmaedje** [comment]
The README can be changed with a minor-fix PR once this is addressed upstream.

**Comment by a-kkiri** [comment]
Thanks for your feedback, I'll make changes later.
