### ISSUE TITLE
Referencing a Table (tablex)

### ISSUE THREAD

**Issue by boyen-cell** [typst/packages#56]
When trying to add the `<reference-label>` to the table and then @referencing it, I get the error "cannot reference sequence".

![image](https://github.com/typst/packages/assets/29734238/e9d709c5-2326-4d74-9433-d5d8aa596f8b)

I've also tried putting everything into a #figure(), but that just leads to weird issues:
![image](https://github.com/typst/packages/assets/29734238/2b166883-02f1-48be-ad40-f77188d72291)
(there's also a completely empty page btwn the "Appendix" heading and the table, which is only there when wrapping it in #figure(). I've set the repeat-heading setting to true, which worked well in the non-#figure()-wrapped version.)

**Comment by slashformotion** [comment]
you might want to submit this issue to https://github.com/PgBiel/typst-tablex

**Comment by laurmaedje** [comment]
There is already this issue at tablex's repository: https://github.com/PgBiel/typst-tablex/issues/7

I'm going to close this here.
