### ISSUE TITLE
Suggestion: versions as subdirectories

### ISSUE THREAD

**Issue by classabbyamp** [typst/packages#61]
I've worked with large monorepos that have thousands of entries in a single directory before (namely https://github.com/void-linux/void-packages), and it becomes unfun pretty quickly when trying to do `blame`s or `log`s on parts of the tree. To prevent issues like this, I'd suggest moving to a layout like this:

```
packages/
    namespace/
        package_name/
            1.0.1/
            1.2.1/
```
this should help prevent things from getting out of control

**Comment by laurmaedje** [comment]
One unfortunate effect of that is that the directory layout diverges between this repository and the directories Typst recognizes/uses on local installations. Unless we change that too, which would be a breaking change.
