### ISSUE TITLE
Minimum Typst Version key

### ISSUE THREAD

**Issue by Mc-Zen** [typst/packages#74]
I think, it would be useful to have a way of specifying the minimum typst version for a package. Many packages or at least newer releases might only work on the more recent Typst versions and fail without giving any helpful error messages with an old compiler. 

I can think of two ways to achieve this: 
- Typst could take the responsibility of checking the version when importing packages and another optional field is added to `typst.toml`. The question would be how Typst gets the version information (definitely possible but likely some work). 
- A much simpler solution would be Typst providing a function to obtain the current version (and possible a helper for determining if the version is less than some specified one) and the packages can then emit a reasonable error message if the version is not supported. 

Just some thoughts. This is not too urgent but will come up sooner or later :)

**Comment by slashformotion** [comment]
this should be added. Sooner or later we will encounter problem if package use things like `dedup` that are not in previous releases

**Comment by laurmaedje** [comment]
I implemented a new `typst.toml` field called `compiler` that specifies the minimum compatible compiler version. The compiler also already supports it (https://github.com/typst/typst/commit/2f672b4e2ebb040896c7a6af5104f72b075565e0). When a package has a too high version, it errors out with a message like: `package requires typst 1.0.0 or newer (current version is 0.7.0)`.
