### ISSUE TITLE
Git submodules instead of monorepo

### ISSUE THREAD

**Issue by Servostar** [typst/packages#825]
### Description

I find the current monorepo structure uncomfortable to work with. Every change in a package has to be contributed directly here.
Which is not a problem by itself. What I find frustrating is that many packages have their own repositories which are, other than by content, not related to the package in this repository. In other words, if I want to do a change to one package I would need to open two PRs: one here and one for the official repository of the package. Or the owner of the package is dedicated enough to commit my change from his/hers repository into this one. That's quite the overhead.

How about making the packages submodules and link them to the externally managed repositories. This makes it easier to contribute to packages since the would have dedicated repositories were development takes place.
Additionally the size of this repository could be held to a minimum since the source of the actual packages is not included.
Versioning of packages can be done by checking out specific branches or tags of the submodules. In case a package owner wants to do an "update" here the workflow would stay the same and the owner opens a PR in which the submodule is checked out to the new tag or branch.

Furthermore strict rules could be applied to these repositories such as properly tagging releases or needing a successfully pipeline for testing if template still compiles successfully.

**Comment by elegaanz** [comment]
It is not expected that a PR is made to this repository for every change you make, you are only supposed to copy your package when you want to make a new release. I'm not even sure git submodules would help a lot here, as you would have to create a new submodule in this repository for each new release anyway (or at least for each new package, if we rely on tags as you suggest). Also, the current system keeps the barrier to entry low, as git submodules require a bit more knowledge than just copying files to Git/GitHub.

But this system is far from perfect, and on the long term another solution (that will probably not depend on git at all) will be offered. I'm closing, as support for submodules will probably not be implemented, it would require too much work for something that will ultimately be replaced by a better system.
