### ISSUE TITLE
[Feature Request] Support for GitHub-flavored Markdown Callouts/Alerts in READMEs on Typst Universe

### ISSUE THREAD

**Issue by jdpieck** [typst/packages#949]
### Description

GitHub has support for a Markdown extension called [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). These alerts allow for documentation information to be displayed with distinctive colors and icons to indicate the significance of the content.

Seeing as these are already supported by GitHub and are already being used by package developers ([myself included](https://typst.app/universe/package/oasis-align)), having this capability in Typst Universe would allow for a higher level of parity across platforms for package documentation. 

### The types of alerts being requested would follow the list as provided on [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).
```md
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```

### This displays as...
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

#### Thank you for your consideration!

**Comment by jdpieck** [comment]
Has been reposted to the [webapp issues page](https://github.com/typst/webapp-issues/issues/501)!

**Comment by elegaanz** [comment]
I'm closing this issue to avoid duplicates then, it is indeed better to have in webapp-issues.
