### ISSUE TITLE
typst universe doesn't display recently updated packges

### ISSUE THREAD

**Issue by Enter-tainer** [typst/packages#955]
### Description

https://typst.app/universe/package/quill still stays at 0.3.0. And tiaoma stays at 0.2.0

**Comment by Mc-Zen** [comment]
Interesting, the new versions are available via `import` anyway.

**Comment by Mc-Zen** [comment]
Could the reason lie here?

![image](https://github.com/user-attachments/assets/3b497386-47b9-4363-ba3a-537ff17151c1)

**Comment by Mc-Zen** [comment]
Apparently some workflows have been canceled

![image](https://github.com/user-attachments/assets/b5416e3d-04b1-4303-bb9a-683dee66b2c4)

**Comment by Mc-Zen** [comment]
No, actuall all the new packages don't show up either so probably the universe just has not been updated yet

**Comment by laurmaedje** [comment]
The bug is in a private repo. We'll fix it soon.
